import Rank3KUM.NearTightGeometry

namespace Rank3KUM.Version2

open Set

variable {α : Type*}

/--
Paper v2, Lemma 8.3. Distinct rank-two flats in a rank-three matroid
span the ambient rank. This removes the equal-cardinality hypothesis used
by the legacy `NearTightGeometry` declaration.
-/
theorem eRk_union_eq_three_of_distinct_rankTwo_flats
    (M : Matroid α)
    (hRank : M.eRank = 3)
    {A B : Set α}
    (hAflat : M.IsFlat A)
    (hBflat : M.IsFlat B)
    (hArank : M.eRk A = 2)
    (hBrank : M.eRk B = 2)
    (hAB : A ≠ B) :
    M.eRk (A ∪ B) = 3 := by
  have hBnotA : ¬ B ⊆ A := by
    intro hBA
    have hAnotB : ¬ A ⊆ B := by
      intro hABsub
      exact hAB (Set.Subset.antisymm hABsub hBA)
    obtain ⟨a, haA, haB⟩ := Set.not_subset.mp hAnotB
    have haE : a ∈ M.E := hAflat.subset_ground haA
    have haNotClosure : a ∉ M.closure B := by
      rw [hBflat.closure]
      exact haB
    have hInsertRank : M.eRk (insert a B) = 3 := by
      rw [M.eRk_insert_eq_add_one ⟨haE, haNotClosure⟩, hBrank]
      norm_num
    have hInsertSubset : insert a B ⊆ A := by
      intro x hx
      rcases hx with rfl | hxB
      · exact haA
      · exact hBA hxB
    have hbad : (3 : ℕ∞) ≤ 2 := by
      calc
        (3 : ℕ∞) = M.eRk (insert a B) := hInsertRank.symm
        _ ≤ M.eRk A := M.eRk_mono hInsertSubset
        _ = 2 := hArank
    norm_num at hbad
  obtain ⟨b, hbB, hbA⟩ := Set.not_subset.mp hBnotA
  have hbE : b ∈ M.E := hBflat.subset_ground hbB
  have hbNotClosure : b ∉ M.closure A := by
    rw [hAflat.closure]
    exact hbA
  have hInsertRank : M.eRk (insert b A) = 3 := by
    rw [M.eRk_insert_eq_add_one ⟨hbE, hbNotClosure⟩, hArank]
    norm_num
  have hInsertSubset : insert b A ⊆ A ∪ B := by
    intro x hx
    rcases hx with rfl | hxA
    · exact Or.inr hbB
    · exact Or.inl hxA
  have hLower : 3 ≤ M.eRk (A ∪ B) := by
    rw [← hInsertRank]
    exact M.eRk_mono hInsertSubset
  apply le_antisymm
  · calc
      M.eRk (A ∪ B) ≤ M.eRank := M.eRk_le_eRank _
      _ = 3 := hRank
  · exact hLower

/--
Paper v2, Lemma 8.4. Distinct rank-two flats in a rank-three matroid
intersect in rank at most one.
-/
theorem eRk_inter_le_one_of_distinct_rankTwo_flats
    (M : Matroid α)
    (hRank : M.eRank = 3)
    {A B : Set α}
    (hAflat : M.IsFlat A)
    (hBflat : M.IsFlat B)
    (hArank : M.eRk A = 2)
    (hBrank : M.eRk B = 2)
    (hAB : A ≠ B) :
    M.eRk (A ∩ B) ≤ 1 := by
  have hUnion : M.eRk (A ∪ B) = 3 :=
    eRk_union_eq_three_of_distinct_rankTwo_flats
      M hRank hAflat hBflat hArank hBrank hAB
  have hInterLeTwo : M.eRk (A ∩ B) ≤ 2 := by
    calc
      M.eRk (A ∩ B) ≤ M.eRk A := M.eRk_mono Set.inter_subset_left
      _ = 2 := hArank
  obtain ⟨r, hr, _hrle⟩ := ENat.le_natCast_iff.mp hInterLeTwo
  have hSub := M.eRk_inter_add_eRk_union_le A B
  rw [hr, hUnion, hArank, hBrank] at hSub
  have hNat : r + 3 ≤ 4 := by
    exact_mod_cast hSub
  rw [hr]
  exact_mod_cast (show r ≤ 1 by omega)

/--
Paper v2, Lemma 8.5. If `e` lies in the nonempty intersection of two
distinct rank-two flats, then their intersection is contained in the
parallel class generated by `e`.
-/
theorem inter_subset_closure_singleton_of_distinct_rankTwo_flats
    (M : Matroid α)
    (hLoopless : M.Loopless)
    (hRank : M.eRank = 3)
    {A B : Set α}
    (hAflat : M.IsFlat A)
    (hBflat : M.IsFlat B)
    (hArank : M.eRk A = 2)
    (hBrank : M.eRk B = 2)
    (hAB : A ≠ B)
    {e : α}
    (he : e ∈ A ∩ B) :
    A ∩ B ⊆ M.closure ({e} : Set α) := by
  let : M.Loopless := hLoopless
  have hInterRank :=
    eRk_inter_le_one_of_distinct_rankTwo_flats
      M hRank hAflat hBflat hArank hBrank hAB
  intro x hx
  by_contra hxClosure
  have heE : e ∈ M.E := hAflat.subset_ground he.1
  have hxE : x ∈ M.E := hAflat.subset_ground hx.1
  have heIndep : M.Indep ({e} : Set α) :=
    (Matroid.isNonloop_of_loopless heE).indep
  have hxe : x ≠ e := by
    intro h
    subst x
    exact hxClosure (M.mem_closure_self e heE)
  have hxNotMem : x ∉ ({e} : Set α) := by
    simpa using hxe
  have hPairIndep : M.Indep (insert x ({e} : Set α)) :=
    (heIndep.notMem_closure_iff_of_notMem hxNotMem hxE).1 hxClosure
  have hPairRank : M.eRk (insert x ({e} : Set α)) = 2 := by
    calc
      M.eRk (insert x ({e} : Set α)) =
          (insert x ({e} : Set α)).encard := hPairIndep.eRk_eq_encard
      _ = 2 := Set.encard_pair hxe
  have hPairSubset : insert x ({e} : Set α) ⊆ A ∩ B := by
    intro u hu
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hu
    rcases hu with rfl | rfl
    · exact hx
    · exact he
  have hbad : (2 : ℕ∞) ≤ 1 := by
    calc
      (2 : ℕ∞) = M.eRk (insert x ({e} : Set α)) := hPairRank.symm
      _ ≤ M.eRk (A ∩ B) := M.eRk_mono hPairSubset
      _ ≤ 1 := hInterRank
  norm_num at hbad

#print axioms Rank3KUM.Version2.eRk_union_eq_three_of_distinct_rankTwo_flats
#print axioms Rank3KUM.Version2.eRk_inter_le_one_of_distinct_rankTwo_flats
#print axioms Rank3KUM.Version2.inter_subset_closure_singleton_of_distinct_rankTwo_flats

end Rank3KUM.Version2
