import Rank3KUM.StrictDensity

namespace Rank3KUM

open Set

variable {α : Type*}

/--
Two distinct finite rank-two flats of the same cardinality span the ambient
rank-three matroid.
-/
theorem eRk_union_eq_three_of_distinct_rankTwo_flats
    (M : Matroid α)
    (hE : M.E.Finite)
    (hRank : M.eRank = 3)
    {A B : Set α}
    (hAflat : M.IsFlat A)
    (hBflat : M.IsFlat B)
    (hArank : M.eRk A = 2)
    (_hBrank : M.eRk B = 2)
    (hAcard : A.ncard = B.ncard)
    (hAB : A ≠ B) :
    M.eRk (A ∪ B) = 3 := by
  have hAfin : A.Finite :=
    hE.subset hAflat.subset_ground
  have hBfin : B.Finite :=
    hE.subset hBflat.subset_ground
  have hBnotA : ¬ B ⊆ A := by
    intro hBA
    have hcardLe : A.encard ≤ B.encard := by
      rw [← hAfin.cast_ncard_eq,
        ← hBfin.cast_ncard_eq, hAcard]
    have hBAeq : B = A :=
      hBfin.eq_of_subset_of_encard_le hBA hcardLe
    exact hAB hBAeq.symm
  obtain ⟨b, hbB, hbA⟩ := Set.not_subset.mp hBnotA
  have hbE : b ∈ M.E :=
    hBflat.subset_ground hbB
  have hbNotClosure : b ∉ M.closure A := by
    rw [hAflat.closure]
    exact hbA
  have hInsertRank : M.eRk (insert b A) = 3 := by
    rw [M.eRk_insert_eq_add_one ⟨hbE, hbNotClosure⟩,
      hArank]
    norm_num
  have hInsertSubset : insert b A ⊆ A ∪ B := by
    intro x hx
    rcases hx with rfl | hxA
    · exact Or.inr hbB
    · exact Or.inl hxA
  have hLower : 3 ≤ M.eRk (A ∪ B) := by
    rw [← hInsertRank]
    exact M.eRk_mono hInsertSubset
  apply le_antisymm
  · calc
      M.eRk (A ∪ B) ≤ M.eRank :=
        M.eRk_le_eRank _
      _ = 3 := hRank
  · exact hLower

/--
Distinct rank-two flats meet in rank at most one: their union already has
ambient rank three, so this is the rank-three form of submodularity.
-/
theorem eRk_inter_le_one_of_distinct_rankTwo_flats
    (M : Matroid α)
    (hE : M.E.Finite)
    (hRank : M.eRank = 3)
    {A B : Set α}
    (hAflat : M.IsFlat A)
    (hBflat : M.IsFlat B)
    (hArank : M.eRk A = 2)
    (hBrank : M.eRk B = 2)
    (hAcard : A.ncard = B.ncard)
    (hAB : A ≠ B) :
    M.eRk (A ∩ B) ≤ 1 := by
  have hUnion :
      M.eRk (A ∪ B) = 3 :=
    eRk_union_eq_three_of_distinct_rankTwo_flats
      M hE hRank hAflat hBflat hArank hBrank
      hAcard hAB
  have hInterLeTwo : M.eRk (A ∩ B) ≤ 2 := by
    calc
      M.eRk (A ∩ B) ≤ M.eRk A :=
        M.eRk_mono Set.inter_subset_left
      _ = 2 := hArank
  obtain ⟨r, hr, _hrle⟩ :=
    ENat.le_natCast_iff.mp hInterLeTwo
  have hSub :=
    M.eRk_inter_add_eRk_union_le A B
  rw [hr, hUnion, hArank, hBrank] at hSub
  have hNat : r + 3 ≤ 4 := by
    exact_mod_cast hSub
  rw [hr]
  exact_mod_cast (show r ≤ 1 by omega)

/--
A nonempty intersection of two distinct rank-two flats is contained in the
parallel class generated by any one of its points.
-/
theorem inter_subset_closure_singleton_of_distinct_rankTwo_flats
    (M : Matroid α)
    (hLoopless : M.Loopless)
    (hE : M.E.Finite)
    (hRank : M.eRank = 3)
    {A B : Set α}
    (hAflat : M.IsFlat A)
    (hBflat : M.IsFlat B)
    (hArank : M.eRk A = 2)
    (hBrank : M.eRk B = 2)
    (hAcard : A.ncard = B.ncard)
    (hAB : A ≠ B)
    {e : α}
    (he : e ∈ A ∩ B) :
    A ∩ B ⊆ M.closure ({e} : Set α) := by
  letI : M.Loopless := hLoopless
  have hInterRank :=
    eRk_inter_le_one_of_distinct_rankTwo_flats
      M hE hRank hAflat hBflat hArank hBrank
      hAcard hAB
  intro x hx
  by_contra hxClosure
  have heE : e ∈ M.E :=
    hAflat.subset_ground he.1
  have hxE : x ∈ M.E :=
    hAflat.subset_ground hx.1
  have heIndep : M.Indep ({e} : Set α) :=
    (Matroid.isNonloop_of_loopless heE).indep
  have hxe : x ≠ e := by
    intro h
    subst x
    exact hxClosure (M.mem_closure_self e heE)
  have hxNotMem : x ∉ ({e} : Set α) := by
    simpa using hxe
  have hPairIndep :
      M.Indep (insert x ({e} : Set α)) :=
    (heIndep.notMem_closure_iff_of_notMem
      hxNotMem hxE).1 hxClosure
  have hPairRank :
      M.eRk (insert x ({e} : Set α)) = 2 := by
    calc
      M.eRk (insert x ({e} : Set α)) =
          (insert x ({e} : Set α)).encard :=
        hPairIndep.eRk_eq_encard
      _ = 2 := Set.encard_pair hxe
  have hPairSubset :
      insert x ({e} : Set α) ⊆ A ∩ B := by
    intro u hu
    simp only [Set.mem_insert_iff,
      Set.mem_singleton_iff] at hu
    rcases hu with rfl | rfl
    · exact hx
    · exact he
  have hbad : (2 : ℕ∞) ≤ 1 := by
    calc
      (2 : ℕ∞) =
          M.eRk (insert x ({e} : Set α)) :=
        hPairRank.symm
      _ ≤ M.eRk (A ∩ B) :=
        M.eRk_mono hPairSubset
      _ ≤ 1 := hInterRank
  norm_num at hbad

/--
In a loopless matroid, the parallel class of a point outside a flat is
disjoint from that flat.
-/
theorem closure_singleton_inter_flat_eq_empty_of_not_mem
    (M : Matroid α)
    (hLoopless : M.Loopless)
    {F : Set α}
    (hFflat : M.IsFlat F)
    {e : α}
    (_heE : e ∈ M.E)
    (heF : e ∉ F) :
    M.closure ({e} : Set α) ∩ F = ∅ := by
  letI : M.Loopless := hLoopless
  apply Set.eq_empty_iff_forall_notMem.2
  intro x hx
  have hxE : x ∈ M.E :=
    M.mem_ground_of_mem_closure hx.1
  have hxNonloop : M.IsNonloop x :=
    Matroid.isNonloop_of_loopless hxE
  have heClosureX :
      e ∈ M.closure ({x} : Set α) :=
    hxNonloop.mem_closure_singleton hx.1
  have hClosureXSubsetF :
      M.closure ({x} : Set α) ⊆ F := by
    calc
      M.closure ({x} : Set α) ⊆ M.closure F :=
        M.closure_subset_closure (by simpa using hx.2)
      _ = F := hFflat.closure
  exact heF (hClosureXSubsetF heClosureX)

#print axioms Rank3KUM.closure_singleton_inter_flat_eq_empty_of_not_mem

/--
If a near-tight family has no common point, any one member can be extended to
three pairwise-distinct members with empty triple intersection.
-/
theorem exists_nonconcurrent_three_nearTight
    (M : Matroid α) (k : ℕ)
    (hk : 3 ≤ k)
    (hLoopless : M.Loopless)
    (hE : M.E.Finite)
    (hRank : M.eRank = 3)
    (hEcard : M.E.encard = ((3 * k : ℕ) : ℕ∞))
    (hStrict : StrictlyUniformlyDense M k)
    (hExists :
      ∃ A : Set α, A ⊆ M.E ∧
        M.eRk A = 2 ∧
        A.ncard = 2 * k - 1)
    (hNoCommon :
      ¬ ∃ e : α, e ∈ M.E ∧
        ∀ A : Set α, A ⊆ M.E →
          M.eRk A = 2 →
          A.ncard = 2 * k - 1 →
          e ∈ A) :
    ∃ A B C : Set α,
      (A ⊆ M.E ∧ M.eRk A = 2 ∧
        A.ncard = 2 * k - 1) ∧
      (B ⊆ M.E ∧ M.eRk B = 2 ∧
        B.ncard = 2 * k - 1) ∧
      (C ⊆ M.E ∧ M.eRk C = 2 ∧
        C.ncard = 2 * k - 1) ∧
      A ≠ B ∧ A ≠ C ∧ B ≠ C ∧
      (A ∩ B) ∩ C = ∅ := by
  obtain ⟨A, hAE, hArank, hAcard⟩ := hExists
  have hAnonempty : A.Nonempty := by
    apply Set.nonempty_iff_ne_empty.2
    intro hAempty
    rw [hAempty] at hAcard
    simp at hAcard
    omega
  obtain ⟨a, haA⟩ := hAnonempty
  have hFailA :
      ∃ B : Set α, B ⊆ M.E ∧
        M.eRk B = 2 ∧
        B.ncard = 2 * k - 1 ∧
        a ∉ B := by
    by_contra hFail
    apply hNoCommon
    refine ⟨a, hAE haA, ?_⟩
    intro B hBE hBrank hBcard
    by_contra haB
    exact hFail ⟨B, hBE, hBrank, hBcard, haB⟩
  obtain ⟨B, hBE, hBrank, hBcard, haB⟩ :=
    hFailA
  have hAB : A ≠ B := by
    intro h
    subst B
    exact haB haA
  have hABnonempty : (A ∩ B).Nonempty :=
    inter_nonempty_of_nearTight
      M k hk hE hEcard hAE hBE hAcard hBcard
  obtain ⟨x, hxAB⟩ := hABnonempty
  have hFailX :
      ∃ C : Set α, C ⊆ M.E ∧
        M.eRk C = 2 ∧
        C.ncard = 2 * k - 1 ∧
        x ∉ C := by
    by_contra hFail
    apply hNoCommon
    refine ⟨x, hAE hxAB.1, ?_⟩
    intro C hCE hCrank hCcard
    by_contra hxC
    exact hFail ⟨C, hCE, hCrank, hCcard, hxC⟩
  obtain ⟨C, hCE, hCrank, hCcard, hxC⟩ :=
    hFailX
  have hAC : A ≠ C := by
    intro h
    subst C
    exact hxC hxAB.1
  have hBC : B ≠ C := by
    intro h
    subst C
    exact hxC hxAB.2
  have hAflat : M.IsFlat A :=
    isFlat_of_strict_rankTwo_ncard_eq
      M k hE hRank hStrict hAE hArank hAcard
  have hBflat : M.IsFlat B :=
    isFlat_of_strict_rankTwo_ncard_eq
      M k hE hRank hStrict hBE hBrank hBcard
  have hCflat : M.IsFlat C :=
    isFlat_of_strict_rankTwo_ncard_eq
      M k hE hRank hStrict hCE hCrank hCcard
  have hABClosure :
      A ∩ B ⊆ M.closure ({x} : Set α) :=
    inter_subset_closure_singleton_of_distinct_rankTwo_flats
      M hLoopless hE hRank hAflat hBflat
      hArank hBrank (by omega) hAB hxAB
  have hClosureDisjoint :
      M.closure ({x} : Set α) ∩ C = ∅ :=
    closure_singleton_inter_flat_eq_empty_of_not_mem
      M hLoopless hCflat (hAE hxAB.1) hxC
  have hABCempty : (A ∩ B) ∩ C = ∅ := by
    apply Set.eq_empty_iff_forall_notMem.2
    intro y hy
    have hyClosure :
        y ∈ M.closure ({x} : Set α) :=
      hABClosure hy.1
    have hyDisjoint :
        y ∈ M.closure ({x} : Set α) ∩ C :=
      ⟨hyClosure, hy.2⟩
    rw [hClosureDisjoint] at hyDisjoint
    exact hyDisjoint
  exact ⟨A, B, C,
    ⟨hAE, hArank, hAcard⟩,
    ⟨hBE, hBrank, hBcard⟩,
    ⟨hCE, hCrank, hCcard⟩,
    hAB, hAC, hBC, hABCempty⟩

#print axioms Rank3KUM.exists_nonconcurrent_three_nearTight

/--
The intersection of two distinct near-tight rank-two flats has at most the
strict rank-one maximum of `k - 1` elements.
-/
theorem ncard_inter_le_k_sub_one_of_distinct_nearTight
    (M : Matroid α) (k : ℕ)
    (hk : 3 ≤ k)
    (hLoopless : M.Loopless)
    (hE : M.E.Finite)
    (hRank : M.eRank = 3)
    (hEcard : M.E.encard = ((3 * k : ℕ) : ℕ∞))
    (hStrict : StrictlyUniformlyDense M k)
    {A B : Set α}
    (hAE : A ⊆ M.E)
    (hBE : B ⊆ M.E)
    (hArank : M.eRk A = 2)
    (hBrank : M.eRk B = 2)
    (hAcard : A.ncard = 2 * k - 1)
    (hBcard : B.ncard = 2 * k - 1)
    (hAB : A ≠ B) :
    (A ∩ B).ncard ≤ k - 1 := by
  letI : M.Loopless := hLoopless
  have hAflat : M.IsFlat A :=
    isFlat_of_strict_rankTwo_ncard_eq
      M k hE hRank hStrict hAE hArank hAcard
  have hBflat : M.IsFlat B :=
    isFlat_of_strict_rankTwo_ncard_eq
      M k hE hRank hStrict hBE hBrank hBcard
  have hInterNonempty : (A ∩ B).Nonempty :=
    inter_nonempty_of_nearTight
      M k hk hE hEcard hAE hBE hAcard hBcard
  have hInterRankLe : M.eRk (A ∩ B) ≤ 1 :=
    eRk_inter_le_one_of_distinct_rankTwo_flats
      M hE hRank hAflat hBflat hArank hBrank
      (by omega) hAB
  have hInterNonempty' := hInterNonempty
  obtain ⟨x, hx⟩ := hInterNonempty
  have hxE : x ∈ M.E := hAE hx.1
  have hxIndep : M.Indep ({x} : Set α) :=
    (Matroid.isNonloop_of_loopless hxE).indep
  have hSingletonRank : M.eRk ({x} : Set α) = 1 := by
    simpa using hxIndep.eRk_eq_encard
  have hInterRankGe : (1 : ℕ∞) ≤ M.eRk (A ∩ B) := by
    rw [← hSingletonRank]
    exact M.eRk_mono (Set.singleton_subset_iff.2 hx)
  have hInterRank : M.eRk (A ∩ B) = 1 :=
    le_antisymm hInterRankLe hInterRankGe
  have hInterFinite : (A ∩ B).Finite :=
    hE.subset (Set.inter_subset_left.trans hAE)
  have hInterProper : A ∩ B ≠ M.E := by
    intro hEq
    have hGroundRank : M.eRk (A ∩ B) = M.eRank := by
      rw [hEq, M.eRk_ground]
    rw [hInterRank, hRank] at hGroundRank
    norm_num at hGroundRank
  have hLt :=
    StrictlyUniformlyDense.encard_lt_k_of_eRk_eq_one
      M k hStrict (Set.inter_subset_left.trans hAE)
      hInterNonempty' hInterProper hInterRank
  have hNatLt : (A ∩ B).ncard < k := by
    rw [← hInterFinite.cast_ncard_eq] at hLt
    exact_mod_cast hLt
  omega

#print axioms Rank3KUM.ncard_inter_le_k_sub_one_of_distinct_nearTight

/--
Three pairwise-distinct nonconcurrent near-tight flats saturate all three
strict rank-one intersection bounds, and their union is the whole ground set.
-/
theorem pairwise_intersections_ncard_eq_of_three_nearTight
    (M : Matroid α) (k : ℕ)
    (hk : 3 ≤ k)
    (hLoopless : M.Loopless)
    (hE : M.E.Finite)
    (hRank : M.eRank = 3)
    (hEcard : M.E.encard = ((3 * k : ℕ) : ℕ∞))
    (hStrict : StrictlyUniformlyDense M k)
    {A B C : Set α}
    (hAE : A ⊆ M.E)
    (hBE : B ⊆ M.E)
    (hCE : C ⊆ M.E)
    (hArank : M.eRk A = 2)
    (hBrank : M.eRk B = 2)
    (hCrank : M.eRk C = 2)
    (hAcard : A.ncard = 2 * k - 1)
    (hBcard : B.ncard = 2 * k - 1)
    (hCcard : C.ncard = 2 * k - 1)
    (hAB : A ≠ B)
    (hAC : A ≠ C)
    (hBC : B ≠ C)
    (hABCempty : (A ∩ B) ∩ C = ∅) :
    (A ∩ B).ncard = k - 1 ∧
      (A ∩ C).ncard = k - 1 ∧
      (B ∩ C).ncard = k - 1 ∧
      (A ∪ B ∪ C).ncard = 3 * k := by
  have hAfin : A.Finite := hE.subset hAE
  have hBfin : B.Finite := hE.subset hBE
  have hCfin : C.Finite := hE.subset hCE
  have hABle : (A ∩ B).ncard ≤ k - 1 :=
    ncard_inter_le_k_sub_one_of_distinct_nearTight
      M k hk hLoopless hE hRank hEcard hStrict
      hAE hBE hArank hBrank hAcard hBcard hAB
  have hACle : (A ∩ C).ncard ≤ k - 1 :=
    ncard_inter_le_k_sub_one_of_distinct_nearTight
      M k hk hLoopless hE hRank hEcard hStrict
      hAE hCE hArank hCrank hAcard hCcard hAC
  have hBCle : (B ∩ C).ncard ≤ k - 1 :=
    ncard_inter_le_k_sub_one_of_distinct_nearTight
      M k hk hLoopless hE hRank hEcard hStrict
      hBE hCE hBrank hCrank hBcard hCcard hBC
  have hPairDisjoint :
      Disjoint (A ∩ C) (B ∩ C) := by
    apply Set.disjoint_left.2
    intro x hxAC hxBC
    have hxABC : x ∈ (A ∩ B) ∩ C :=
      ⟨⟨hxAC.1, hxBC.1⟩, hxAC.2⟩
    rw [hABCempty] at hxABC
    exact hxABC
  have hDistrib :
      (A ∪ B) ∩ C = (A ∩ C) ∪ (B ∩ C) := by
    ext x
    simp only [Set.mem_inter_iff, Set.mem_union]
    tauto
  have hMiddleCard :
      ((A ∪ B) ∩ C).ncard =
        (A ∩ C).ncard + (B ∩ C).ncard := by
    rw [hDistrib]
    exact Set.ncard_union_eq hPairDisjoint
      (hAfin.inter_of_left C) (hBfin.inter_of_left C)
  have hEncard : M.E.ncard = 3 * k := by
    have hcast :
        (M.E.ncard : ℕ∞) = ((3 * k : ℕ) : ℕ∞) := by
      rw [hE.cast_ncard_eq]
      exact hEcard
    exact_mod_cast hcast
  have hUnionLe :
      (A ∪ B ∪ C).ncard ≤ 3 * k := by
    rw [← hEncard]
    exact Set.ncard_le_ncard
      (Set.union_subset
        (Set.union_subset hAE hBE) hCE) hE
  have hCountAB :=
    Set.ncard_union_add_ncard_inter A B hAfin hBfin
  have hCountABC :=
    Set.ncard_union_add_ncard_inter
      (A ∪ B) C (hAfin.union hBfin) hCfin
  rw [hAcard, hBcard] at hCountAB
  rw [hMiddleCard, hCcard] at hCountABC
  constructor
  · omega
  constructor
  · omega
  constructor <;> omega

#print axioms Rank3KUM.pairwise_intersections_ncard_eq_of_three_nearTight

/--
No near-tight rank-two flat can avoid representatives of all three pairwise
intersections of a nonconcurrent near-tight triple.
-/
theorem false_of_nearTight_avoids_three_pairwise_representatives
    (M : Matroid α) (k : ℕ)
    (hk : 3 ≤ k)
    (hLoopless : M.Loopless)
    (hE : M.E.Finite)
    (hRank : M.eRank = 3)
    (hEcard : M.E.encard = ((3 * k : ℕ) : ℕ∞))
    (hStrict : StrictlyUniformlyDense M k)
    {A B C H : Set α}
    (hAE : A ⊆ M.E)
    (hBE : B ⊆ M.E)
    (hCE : C ⊆ M.E)
    (hHE : H ⊆ M.E)
    (hArank : M.eRk A = 2)
    (hBrank : M.eRk B = 2)
    (hCrank : M.eRk C = 2)
    (hHrank : M.eRk H = 2)
    (hAcard : A.ncard = 2 * k - 1)
    (hBcard : B.ncard = 2 * k - 1)
    (hCcard : C.ncard = 2 * k - 1)
    (hHcard : H.ncard = 2 * k - 1)
    (hAB : A ≠ B)
    (hAC : A ≠ C)
    (hBC : B ≠ C)
    (hABCempty : (A ∩ B) ∩ C = ∅)
    {x y z : α}
    (hx : x ∈ A ∩ B)
    (hy : y ∈ A ∩ C)
    (hz : z ∈ B ∩ C)
    (hxH : x ∉ H)
    (hyH : y ∉ H)
    (hzH : z ∉ H) :
    False := by
  have hAfin : A.Finite := hE.subset hAE
  have hBfin : B.Finite := hE.subset hBE
  have hCfin : C.Finite := hE.subset hCE
  have hABfin : (A ∩ B).Finite := hAfin.inter_of_left B
  have hACfin : (A ∩ C).Finite := hAfin.inter_of_left C
  have hBCfin : (B ∩ C).Finite := hBfin.inter_of_left C
  have hAflat : M.IsFlat A :=
    isFlat_of_strict_rankTwo_ncard_eq
      M k hE hRank hStrict hAE hArank hAcard
  have hBflat : M.IsFlat B :=
    isFlat_of_strict_rankTwo_ncard_eq
      M k hE hRank hStrict hBE hBrank hBcard
  have hCflat : M.IsFlat C :=
    isFlat_of_strict_rankTwo_ncard_eq
      M k hE hRank hStrict hCE hCrank hCcard
  have hHflat : M.IsFlat H :=
    isFlat_of_strict_rankTwo_ncard_eq
      M k hE hRank hStrict hHE hHrank hHcard
  obtain ⟨hABcard, hACcard, hBCcard, _hUnionCard⟩ :=
    pairwise_intersections_ncard_eq_of_three_nearTight
      M k hk hLoopless hE hRank hEcard hStrict
      hAE hBE hCE hArank hBrank hCrank
      hAcard hBcard hCcard hAB hAC hBC hABCempty
  have hABACDisjoint :
      Disjoint (A ∩ B) (A ∩ C) := by
    apply Set.disjoint_left.2
    intro u huAB huAC
    have huABC : u ∈ (A ∩ B) ∩ C :=
      ⟨huAB, huAC.2⟩
    rw [hABCempty] at huABC
    exact huABC
  have hPairUnionBCDisjoint :
      Disjoint ((A ∩ B) ∪ (A ∩ C)) (B ∩ C) := by
    apply Set.disjoint_left.2
    intro u huUnion huBC
    rcases huUnion with huAB | huAC
    · have huABC : u ∈ (A ∩ B) ∩ C :=
        ⟨huAB, huBC.2⟩
      rw [hABCempty] at huABC
      exact huABC
    · have huABC : u ∈ (A ∩ B) ∩ C :=
        ⟨⟨huAC.1, huBC.1⟩, huAC.2⟩
      rw [hABCempty] at huABC
      exact huABC
  let P : Set α :=
    ((A ∩ B) ∪ (A ∩ C)) ∪ (B ∩ C)
  have hPcard : P.ncard = 3 * k - 3 := by
    dsimp [P]
    rw [Set.ncard_union_eq hPairUnionBCDisjoint
          (hABfin.union hACfin) hBCfin,
        Set.ncard_union_eq hABACDisjoint
          hABfin hACfin,
        hABcard, hACcard, hBCcard]
    omega
  have hPE : P ⊆ M.E := by
    intro u hu
    rcases hu with (huAB | huAC) | huBC
    · exact hAE huAB.1
    · exact hAE huAC.1
    · exact hBE huBC.1
  have hEncard : M.E.ncard = 3 * k := by
    have hcast :
        (M.E.ncard : ℕ∞) = ((3 * k : ℕ) : ℕ∞) := by
      rw [hE.cast_ncard_eq]
      exact hEcard
    exact_mod_cast hcast
  have hResidualCard : (M.E \ P).ncard = 3 := by
    rw [Set.ncard_sdiff' hPE hE, hEncard, hPcard]
    omega
  have hABClosure :
      A ∩ B ⊆ M.closure ({x} : Set α) :=
    inter_subset_closure_singleton_of_distinct_rankTwo_flats
      M hLoopless hE hRank hAflat hBflat
      hArank hBrank (by omega) hAB hx
  have hACClosure :
      A ∩ C ⊆ M.closure ({y} : Set α) :=
    inter_subset_closure_singleton_of_distinct_rankTwo_flats
      M hLoopless hE hRank hAflat hCflat
      hArank hCrank (by omega) hAC hy
  have hBCClosure :
      B ∩ C ⊆ M.closure ({z} : Set α) :=
    inter_subset_closure_singleton_of_distinct_rankTwo_flats
      M hLoopless hE hRank hBflat hCflat
      hBrank hCrank (by omega) hBC hz
  have hXHempty :
      M.closure ({x} : Set α) ∩ H = ∅ :=
    closure_singleton_inter_flat_eq_empty_of_not_mem
      M hLoopless hHflat (hAE hx.1) hxH
  have hYHempty :
      M.closure ({y} : Set α) ∩ H = ∅ :=
    closure_singleton_inter_flat_eq_empty_of_not_mem
      M hLoopless hHflat (hAE hy.1) hyH
  have hZHempty :
      M.closure ({z} : Set α) ∩ H = ∅ :=
    closure_singleton_inter_flat_eq_empty_of_not_mem
      M hLoopless hHflat (hBE hz.1) hzH
  have hHResidual : H ⊆ M.E \ P := by
    intro u huH
    refine ⟨hHE huH, ?_⟩
    intro huP
    rcases huP with (huAB | huAC) | huBC
    · have huEmpty :
          u ∈ M.closure ({x} : Set α) ∩ H :=
        ⟨hABClosure huAB, huH⟩
      rw [hXHempty] at huEmpty
      exact huEmpty
    · have huEmpty :
          u ∈ M.closure ({y} : Set α) ∩ H :=
        ⟨hACClosure huAC, huH⟩
      rw [hYHempty] at huEmpty
      exact huEmpty
    · have huEmpty :
          u ∈ M.closure ({z} : Set α) ∩ H :=
        ⟨hBCClosure huBC, huH⟩
      rw [hZHempty] at huEmpty
      exact huEmpty
  have hHle : H.ncard ≤ 3 := by
    rw [← hResidualCard]
    exact Set.ncard_le_ncard hHResidual hE.sdiff
  rw [hHcard] at hHle
  omega

#print axioms Rank3KUM.false_of_nearTight_avoids_three_pairwise_representatives

/--
For three pairwise-distinct nonconcurrent rank-two flats, representatives of
their three pairwise intersections can be chosen to form a basis.
-/
theorem exists_isBase_of_pairwise_intersections_three_flats
    (M : Matroid α)
    (hLoopless : M.Loopless)
    (hRank : M.eRank = 3)
    {A B C : Set α}
    (hAflat : M.IsFlat A)
    (hBflat : M.IsFlat B)
    (hCflat : M.IsFlat C)
    (hABnonempty : (A ∩ B).Nonempty)
    (hACnonempty : (A ∩ C).Nonempty)
    (hBCnonempty : (B ∩ C).Nonempty)
    (hABCempty : (A ∩ B) ∩ C = ∅) :
    ∃ x ∈ A ∩ B, ∃ y ∈ A ∩ C, ∃ z ∈ B ∩ C,
      M.IsBase ({x, y, z} : Set α) := by
  obtain ⟨x, hx⟩ := hABnonempty
  obtain ⟨y, hy⟩ := hACnonempty
  obtain ⟨z, hz⟩ := hBCnonempty
  have hxNotC : x ∉ C := by
    intro hxC
    have hxABC : x ∈ (A ∩ B) ∩ C :=
      ⟨hx, hxC⟩
    rw [hABCempty] at hxABC
    exact hxABC
  have hyNotB : y ∉ B := by
    intro hyB
    have hyABC : y ∈ (A ∩ B) ∩ C :=
      ⟨⟨hy.1, hyB⟩, hy.2⟩
    rw [hABCempty] at hyABC
    exact hyABC
  have hzNotA : z ∉ A := by
    intro hzA
    have hzABC : z ∈ (A ∩ B) ∩ C :=
      ⟨⟨hzA, hz.1⟩, hz.2⟩
    rw [hABCempty] at hzABC
    exact hzABC
  letI : M.Loopless := hLoopless
  have hxE : x ∈ M.E :=
    hAflat.subset_ground hx.1
  have hyE : y ∈ M.E :=
    hAflat.subset_ground hy.1
  have hzE : z ∈ M.E :=
    hBflat.subset_ground hz.1
  have hyIndep : M.Indep ({y} : Set α) :=
    (Matroid.isNonloop_of_loopless hyE).indep
  have hClosureYSubsetC :
      M.closure ({y} : Set α) ⊆ C := by
    calc
      M.closure ({y} : Set α) ⊆ M.closure C :=
        M.closure_subset_closure (by simpa using hy.2)
      _ = C := hCflat.closure
  have hxNotClosureY :
      x ∉ M.closure ({y} : Set α) :=
    fun hxClosure => hxNotC (hClosureYSubsetC hxClosure)
  have hxy : x ≠ y := by
    intro h
    subst x
    exact hxNotC hy.2
  have hxNotMemY : x ∉ ({y} : Set α) := by
    simpa using hxy
  have hPairIndep :
      M.Indep ({x, y} : Set α) :=
    (hyIndep.notMem_closure_iff_of_notMem
      hxNotMemY hxE).1 hxNotClosureY
  have hPairSubsetA :
      ({x, y} : Set α) ⊆ A := by
    intro u hu
    simp only [Set.mem_insert_iff,
      Set.mem_singleton_iff] at hu
    rcases hu with rfl | rfl
    · exact hx.1
    · exact hy.1
  have hClosurePairSubsetA :
      M.closure ({x, y} : Set α) ⊆ A := by
    calc
      M.closure ({x, y} : Set α) ⊆ M.closure A :=
        M.closure_subset_closure hPairSubsetA
      _ = A := hAflat.closure
  have hzNotClosurePair :
      z ∉ M.closure ({x, y} : Set α) :=
    fun hzClosure => hzNotA
      (hClosurePairSubsetA hzClosure)
  have hzNotMemPair :
      z ∉ ({x, y} : Set α) :=
    fun hzPair => hzNotA (hPairSubsetA hzPair)
  have hInsertIndep :
      M.Indep (insert z ({x, y} : Set α)) :=
    (hPairIndep.notMem_closure_iff_of_notMem
      hzNotMemPair hzE).1 hzNotClosurePair
  have hSetEq :
      insert z ({x, y} : Set α) =
        ({x, y, z} : Set α) := by
    ext u
    simp [or_comm, or_left_comm, or_assoc]
  have hTripleIndep :
      M.Indep ({x, y, z} : Set α) := by
    rwa [hSetEq] at hInsertIndep
  have hxz : x ≠ z := by
    intro h
    subst x
    exact hzNotA hx.1
  have hyz : y ≠ z := by
    intro h
    subst y
    exact hzNotA hy.1
  have hTripleCard :
      ({x, y, z} : Set α).encard = 3 := by
    rw [Set.encard_insert_of_notMem]
    · rw [Set.encard_pair hyz]
      norm_num
    · simp [hxy, hxz]
  have hTripleFinite :
      ({x, y, z} : Set α).Finite :=
    Set.finite_of_encard_eq_coe hTripleCard
  have hTripleBase :
      M.IsBase ({x, y, z} : Set α) := by
    apply hTripleIndep.isBase_of_eRk_ge hTripleFinite
    exact (calc
      M.eRank = 3 := hRank
      _ = ({x, y, z} : Set α).encard :=
        hTripleCard.symm
      _ = M.eRk ({x, y, z} : Set α) :=
        hTripleIndep.eRk_eq_encard.symm).le
  exact ⟨x, hx, y, hy, z, hz, hTripleBase⟩

#print axioms Rank3KUM.exists_isBase_of_pairwise_intersections_three_flats

/--
Every strictly uniformly dense rank-three instance with `k ≥ 3` has a basis
that hits every near-tight rank-two flat.
-/
theorem exists_isBase_hitsNearTight_of_strict_rankThree
    (M : Matroid α) (k : ℕ)
    (hk : 3 ≤ k)
    (hLoopless : M.Loopless)
    (hE : M.E.Finite)
    (hRank : M.eRank = 3)
    (hEcard : M.E.encard = ((3 * k : ℕ) : ℕ∞))
    (hStrict : StrictlyUniformlyDense M k) :
    ∃ D : Set α,
      M.IsBase D ∧ HitsNearTightRankTwo M k D := by
  by_cases hExists :
      ∃ A : Set α, A ⊆ M.E ∧
        M.eRk A = 2 ∧
        A.ncard = 2 * k - 1
  · by_cases hCommon :
        ∃ e : α, e ∈ M.E ∧
          ∀ A : Set α, A ⊆ M.E →
            M.eRk A = 2 →
            A.ncard = 2 * k - 1 →
            e ∈ A
    · exact
        exists_isBase_hitsNearTight_of_common_point
          M k hLoopless hCommon
    · obtain ⟨A, B, C, hA, hB, hC,
          hAB, hAC, hBC, hABCempty⟩ :=
        exists_nonconcurrent_three_nearTight
          M k hk hLoopless hE hRank hEcard
          hStrict hExists hCommon
      rcases hA with ⟨hAE, hArank, hAcard⟩
      rcases hB with ⟨hBE, hBrank, hBcard⟩
      rcases hC with ⟨hCE, hCrank, hCcard⟩
      have hAflat : M.IsFlat A :=
        isFlat_of_strict_rankTwo_ncard_eq
          M k hE hRank hStrict hAE hArank hAcard
      have hBflat : M.IsFlat B :=
        isFlat_of_strict_rankTwo_ncard_eq
          M k hE hRank hStrict hBE hBrank hBcard
      have hCflat : M.IsFlat C :=
        isFlat_of_strict_rankTwo_ncard_eq
          M k hE hRank hStrict hCE hCrank hCcard
      have hABnonempty : (A ∩ B).Nonempty :=
        inter_nonempty_of_nearTight
          M k hk hE hEcard hAE hBE hAcard hBcard
      have hACnonempty : (A ∩ C).Nonempty :=
        inter_nonempty_of_nearTight
          M k hk hE hEcard hAE hCE hAcard hCcard
      have hBCnonempty : (B ∩ C).Nonempty :=
        inter_nonempty_of_nearTight
          M k hk hE hEcard hBE hCE hBcard hCcard
      obtain ⟨x, hx, y, hy, z, hz, hD⟩ :=
        exists_isBase_of_pairwise_intersections_three_flats
          M hLoopless hRank hAflat hBflat hCflat
          hABnonempty hACnonempty hBCnonempty hABCempty
      refine ⟨({x, y, z} : Set α), hD, ?_⟩
      intro H hHE hHrank hHcard
      apply Set.nonempty_iff_ne_empty.2
      intro hHitEmpty
      have hxH : x ∉ H := by
        intro hxH
        have hxHit :
            x ∈ H ∩ ({x, y, z} : Set α) :=
          ⟨hxH, by simp⟩
        rw [hHitEmpty] at hxHit
        exact hxHit
      have hyH : y ∉ H := by
        intro hyH
        have hyHit :
            y ∈ H ∩ ({x, y, z} : Set α) :=
          ⟨hyH, by simp⟩
        rw [hHitEmpty] at hyHit
        exact hyHit
      have hzH : z ∉ H := by
        intro hzH
        have hzHit :
            z ∈ H ∩ ({x, y, z} : Set α) :=
          ⟨hzH, by simp⟩
        rw [hHitEmpty] at hzHit
        exact hzHit
      exact
        false_of_nearTight_avoids_three_pairwise_representatives
          M k hk hLoopless hE hRank hEcard hStrict
          hAE hBE hCE hHE hArank hBrank hCrank hHrank
          hAcard hBcard hCcard hHcard
          hAB hAC hBC hABCempty hx hy hz hxH hyH hzH
  · exact
      exists_isBase_hitsNearTight_of_no_nearTight
        M k hExists

#print axioms Rank3KUM.exists_isBase_hitsNearTight_of_strict_rankThree

#print axioms Rank3KUM.inter_subset_closure_singleton_of_distinct_rankTwo_flats

#print axioms Rank3KUM.eRk_inter_le_one_of_distinct_rankTwo_flats

#print axioms Rank3KUM.eRk_union_eq_three_of_distinct_rankTwo_flats

end Rank3KUM
